/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from "three"

export function HandFilled(props) {
  const { nodes, materials } = useGLTF('/3d/card-embra/hand-embra-fiiled.glb')

  const opacityMaterial = useMemo(() => {
    const material = new THREE.MeshBasicMaterial({
      opacity: props.opacity,
      transparent: true,
      color: materials.filled.color, // Copy properties you need
      map: materials.filled.map
    })

    return material;
  }, [props.opacity])

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3004'].geometry}
        material={opacityMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3001'].geometry}
        material={opacityMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3002'].geometry}
        material={opacityMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3003'].geometry}
        material={opacityMaterial}
      />
    </group>
  )
}

useGLTF.preload('/3d/card-embra/hand-embra-fiiled.glb')
