/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HandStroke(props) {
  const { nodes, materials } = useGLTF('/3d/card-embra/hand-embra-stroke.glb')
  return (
     <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-4002'].geometry}
        material={materials.filled}
        position={[-0.051, 0.146, 0.006]}
        rotation={[Math.PI / 2, 0.03, 0]}
        scale={4.673}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3004'].geometry}
        material={materials.filled}
        position={[0.112, 0.179, 0.006]}
        rotation={[Math.PI / 2, 0.03, 0]}
        scale={[4.673, 0.935, 4.673]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3007'].geometry}
        material={materials.filled}
        position={[0.08, 0.233, 0.006]}
        rotation={[Math.PI / 2, 0.03, 0]}
        scale={[4.673, 0.935, 4.673]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hand-3005'].geometry}
        material={materials.filled}
        position={[0.092, 0.294, 0.012]}
        rotation={[Math.PI / 2, 0.03, 0]}
        scale={[4.673, 0.935, 4.673]}
      />
    </group>
  )
}

useGLTF.preload('/3d/card-embra/hand-embra-stroke.glb')
