/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import fragment from "!!raw-loader!../../../shaders/gradient/fragment.glsl";
import vertex from "!!raw-loader!../../../shaders/gradient/vertex.glsl";
import { MeshPortalMaterial, RoundedBox, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { Batman } from "../../../assets/3d/Batman";

export function Tag(props) {
  const batmanRef = useRef();
  const tRef = useRef();

  const { nodes, materials } = useGLTF("/3d/card-embra/tag.glb");

  const uniforms = useMemo(
    () => ({
      u_time: { value: 0 },
      u_resolution: { value: new THREE.Vector2(1.0, 1.0) }, // Intensidade da distorção
      u_speed: { value: 1.0 },
      u_wave_intensity: { value: 5.5 },
      u_color_shift: { value: 0.7 },
    }),
    []
  );

  useEffect(() => {
    if(tRef.current) console.log(tRef.current)
  }, [tRef.current])

  useFrame((state) => {
    const time = state.clock.getElapsedTime();
    batmanRef.current.rotation.y = Math.cos(time * 0.5) / 2;
    // console.log(batmanRef.current.position.z);
  });

  return (
    <group {...props} dispose={null} position={[0, -0.5, 0]}>
      <mesh
        name="card"
        castShadow
        receiveShadow
        geometry={nodes.card.geometry}
        material={materials.base}
        ref={tRef}
      >
        <MeshPortalMaterial side={2}>
          <ambientLight intensity={10} />
          
          <Batman ref={batmanRef} scale={0.4} position={[0, 0.1, 0.1]} />

          <mesh position={[0, -3, -3]} scale={10}>
            <boxGeometry args={[9, 9, 0.1]} />
            <shaderMaterial
              vertexShader={vertex}
              fragmentShader={fragment}
              side={2}
            />
          </mesh>
        </MeshPortalMaterial>
      </mesh>

      <mesh
        name="clip"
        castShadow
        receiveShadow
        geometry={nodes.clip.geometry}
        material={materials.metal}
      />
      <mesh
        name="clamp"
        castShadow
        receiveShadow
        geometry={nodes.clamp.geometry}
        material={materials.metal}
      />
    </group>
  );
}

useGLTF.preload("/3d/card-embra/tag.glb");
