/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import fragment from "!!raw-loader!../../../shaders/holographic/fragment.glsl";
import vertex from "!!raw-loader!../../../shaders/holographic/vertex.glsl";
import vertexGradient from "!!raw-loader!../../../shaders/gradient/vertex.glsl";
import fragmentGradient from "!!raw-loader!../../../shaders/gradient/fragment.glsl";
import { MeshPortalMaterial, RoundedBox, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import * as THREE from "three";
import { Batman } from "../../../assets/3d/Batman";
import {HandFilled} from "./HandFilled";
import {HandStroke} from "./HandStroke";

export function Tag(props) {
  const batmanRef = useRef();
  const tRef = useRef();

  const { nodes, materials } = useGLTF("/3d/card-embra/newCard.glb");

  const uniforms = useMemo(
    () => ({
      uTexture: { value: nodes.bottom.material },
      u_time: { value: 0 },
      u_resolution: { value: new THREE.Vector2(1.0, 1.0) }, // Intensidade da distorção
      u_speed: { value: 1.0 },
      u_wave_intensity: { value: 5.5 },
      u_color_shift: { value: 0.7 },
    }),
    []
  );

  const shaderMaterial = useMemo(() =>
    new THREE.ShaderMaterial({
      vertexShader: vertex,
      fragmentShader: fragment,
      uniforms: uniforms,
      side: THREE.FrontSide,
      transparent: true,
    }), [vertex, fragment, uniforms]
  );

  useEffect(() => {
    // if (tRef.current) console.log(tRef.current)
  }, [tRef.current])

  useFrame((state) => {
    const time = state.clock.getElapsedTime();
    // batmanRef.current.rotation.y = Math.cos(time * 0.5) / 2;
    // console.log(batmanRef.current.position.z);

    if (tRef.current && tRef.current.material) {
      tRef.current.material.uniforms.u_time.value = props.camera.current.object.position.x * 3.0;
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hand.geometry}
        material={shaderMaterial}
        position={[0.282, 0.967, 0.006]}
        rotation={[Math.PI / 2, 0.03, 0]}
      />

      <mesh
        castShadow
        receiveShadow
        ref={tRef}
        geometry={nodes.bottom.geometry}
        material={shaderMaterial}
        position={[-0.295, 0.093, 0.006]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      <group position={[-0.005, 0.655, 0.003]}>
        {/* Front side with portal */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card.geometry}
        >
          <MeshPortalMaterial side={THREE.FrontSide}>
            <ambientLight intensity={20} />

            <HandFilled scale={3.5} position={[0.2, -0.95, -0.5]} opacity={0.1} />
            <HandFilled scale={3} position={[-0.35, -1, -0.3]} opacity={0.9}/>

            <mesh position={[0, -1.5, -1]} scale={10}>
              <boxGeometry args={[10, 10, 0.1]} />
              <shaderMaterial
                vertexShader={vertexGradient}
                fragmentShader={fragmentGradient}
              />
            </mesh>
          </MeshPortalMaterial>
        </mesh>

        {/* Back side with regular material */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card.geometry}
          material={materials.base}
          position={[0, 0, -0.005]}
        />
      </group>

      <mesh castShadow receiveShadow geometry={nodes.clamp.geometry} material={materials.metal} />
      <mesh castShadow receiveShadow geometry={nodes.clip.geometry} material={materials.metal} />
    </group>
  );
}

useGLTF.preload("/3d/card-embra/tag.glb");
