/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useLayoutEffect, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier';
import * as THREE from 'three'
import useTextureOptimization from '@/app/hooks/useTextureOptimization';

export function CourtTest(props) {
  const { nodes, materials, scene } = useGLTF('/3d/basket-court-2/test-basket.glb')

  useTextureOptimization(scene)

  const maps = useTexture({
    map: "/3d/basket-court-2/textures/aerial_asphalt_01_diff_4k.jpg",
    // displacementMap: "/3d/basket-court-2/textures/aerial_asphalt_01_disp_4k.jpg",
    aoMap: "/3d/basket-court-2/textures/aerial_asphalt_01_ao_4k.jpg",
    normalMap: "/3d/basket-court-2/textures/aerial_asphalt_01_nor_gl_4k.png",
    roughnessMap: "/3d/basket-court-2/textures/aerial_asphalt_01_rough_4k.jpg",
  })

  useLayoutEffect(() => {
    for (const key in maps) {
      maps[key].wrapS = maps[key].wrapT = THREE.RepeatWrapping; // Set wrap mode to repeat
      maps[key].repeat.set(1, 1); // Set repeat to 1 for both axes
      maps[key].anisotropy = 16; // Set anisotropy for better quality
      maps[key].encoding = THREE.sRGBEncoding; // Set encoding for color maps
    }
  }, [maps])

  return (
    <group {...props} dispose={null} position={[0, 0, 0]}>
      <mesh
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials['Material.002']}
        position={[0, 0.000, 0]}
        scale={[1, 1, 1]}
        anisotropy={16}
      />

      <RigidBody type='fixed' receiveShadow>
        <mesh
          position={[0, -0.01, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1, 1, 1]}
          receiveShadow
        >
          <planeGeometry args={[50, 50, 100, 100]} />
          <meshPhysicalMaterial
            {...maps}
            side={2}
            metalness={0.5}
            displacementScale={0.5}
          />
        </mesh>
      </RigidBody>

    </group>
  )
}

useGLTF.preload('/3d/basket-court-2/test-basket.glb')

