/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wolfboyyang (https://sketchfab.com/wolfboyyang)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/basketball-54d4d2302dd3449e97ace9c29b57ce92
Title: Basketball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d/basket-ball/scene.gltf')
  
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Object_4"
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Bola}
      />
      <mesh
        name="Object_5"
        castShadow
        receiveShadow
        geometry={nodes.Object_5.geometry}
        material={materials.Linhas}
      />
    </group>
  )
}

useGLTF.preload('/3d/basket-ball/scene.gltf')
