/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/3d/batman/batman.gltf 
Author: King_45 (https://sketchfab.com/King_45)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/batman-multiversus-b6a84cca73f647ba8c86df799dd3eef3
Title: Batman | MultiVersus
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React from "react";
import { SkeletonUtils } from "three-stdlib";

export function Batman(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("3d/batman/batman.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.8}
          position={[0, -1.5, 0]}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Batman_Cape1_SkelMesh_389">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name="Batman_Cape1_SkelMesh001_388" />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Batman_mat}
                    skeleton={nodes.Object_7.skeleton}
                    castShadow={true}
                    receiveShadow={true}
                  />
                </group>
              </group>

              <group name="Batman_NoCape_SkelMesh_960">
                <group name="GLTF_created_1">
                  <primitive object={nodes.GLTF_created_1_rootJoint} />
                  <group name="Batman_NoCape_SkelMesh001_959" />
                  <skinnedMesh
                    name="Object_400"
                    geometry={nodes.Object_400.geometry}
                    material={materials.Batman_mat}
                    skeleton={nodes.Object_400.skeleton}
                    castShadow={true}
                    receiveShadow={true}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("3d/batman/batman.gltf");
