/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cube(props) {
  const { nodes, materials } = useGLTF('/3d/cube/untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Material}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/3d/cube/untitled.gltf')
